apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}-jts
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
data:
  jts.ini: |-
    [IBGateway]
    WriteDebug=false
    ApiOnly=true

    [Logon]
    useRemoteSettings=false
    TimeZone=Etc/UTC
    Locale=en
    UseSSL=true

    [Communication]
    Region=ch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
data:
  ibgateway.vmoptions: |-
    -Xmx{{ .Values.jvm.Xmx | default "768" }}m
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis={{ .Values.jvm.XX.MaxGCPauseMillis | default "200" }}
    -XX:ParallelGCThreads={{ .Values.jvm.XX.ParallelGCThreads | default "20" }}
    -XX:ConcGCThreads={{ .Values.jvm.XX.ConcGCThreads | default "5" }}
    -XX:InitiatingHeapOccupancyPercent={{ .Values.jvm.XX.InitiatingHeapOccupancyPercent | default "70" }}
    -Dinstaller.uuid={{ required "UUID JVM requirement" .Values.jvm.installer.uuid }}
    -DvmOptionsPath=/home/trader/Jts/ibgateway/{{ include "ibkr-gateway.version" . }}/ibgateway.vmoptions
    -Dsun.awt.nopixfmt=true
    -Dsun.java2d.noddraw=true
    -Dswing.boldMetal=false
    -Dsun.locale.formatasdefault=true