apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibkr-gateway.fullname" . }}
  labels:
    {{- include "ibkr-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "ibkr-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ibkr-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ibkr-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: vnc
              containerPort: 6080
              protocol: TCP
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: socket
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 500
            periodSeconds: 30
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: {{ include "ibkr-gateway.fullname" . }}-config
              mountPath: /opt/ibc/config.ini
              subPath: config.ini
            - name: {{ include "ibkr-gateway.fullname" . }}-jts
              mountPath: /home/trader/Jts/jts.ini
              subPath: jts.ini
            - name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
              mountPath: /home/trader/Jts/ibgateway/{{ include "ibkr-gateway.version" . }}/ibgateway.vmoptions
              subPath: ibgateway.vmoptions
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "ibkr-gateway.fullname" . }}-config
          secret:
            secretName: {{ required "credentials IBKR is required" .Values.config.IbkrCredentials }}
        - name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
          configMap:
            name: {{ include "ibkr-gateway.fullname" . }}-vmoptions
        - name: {{ include "ibkr-gateway.fullname" . }}-jts
          configMap:
            name: {{ include "ibkr-gateway.fullname" . }}-jts
      {{- if .Values.config.VncCredentials }}
        - name: {{ include "ibkr-gateway.fullname" . }}-vnc
          secret:
            secretName: {{ .Values.config.VncCredentials }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
