---
logOptions:
  level: info
  format: json
socket:
  listen:
    protocol: tcp4
    address: 0.0.0.0:5000
  destination: 
    protocol: tcp6
    address: 127.0.0.1:4001
  timeout: 3s
health:
  listen: 0.0.0.0:3000
  timeout: 3s